# Copyright (C) 2011 The CyanogenMod Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/pantech/ef33s/setup-makefiles.sh

# Prebuilt libraries that are needed to build open-source libraries

# share lib
PRODUCT_COPY_FILES += \
	vendor/pantech/a760s/proprietary/libril.so:obj/lib/libril.so \
	vendor/pantech/a760s/proprietary/libcamera_client.so:obj/lib/libcamera_client.so \
	vendor/pantech/a760s/proprietary/libaudioalsa.so:obj/lib/libaudioalsa.so \
	vendor/pantech/a760s/proprietary/libacdbloader.so:obj/lib/libacdbloader.so \
	vendor/pantech/a760s/proprietary/libacdbmapper.so:obj/lib/libacdbmapper.so \
	vendor/pantech/ef33s/proprietary/lib/libv8.so:obj/lib/libv8.so

# Lib
PRODUCT_COPY_FILES += \
	vendor/pantech/a760s/proprietary/camera.msm8660.so:system/lib/hw/camera.msm8660.so \
	vendor/pantech/a760s/proprietary/sensors.msm8660.so:system/lib/hw/sensors.msm8660.so \
	vendor/pantech/a760s/proprietary/lights.msm8660.so:system/lib/hw/lights.msm8660.so \
	vendor/pantech/a760s/proprietary/eglsubAndroid.so:system/lib/egl/eglsubAndroid.so \
	vendor/pantech/a760s/proprietary/libEGL_adreno200.so:system/lib/egl/libEGL_adreno200.so \
	vendor/pantech/a760s/proprietary/libGLES_android.so:system/lib/egl/libGLES_android.so \
	vendor/pantech/a760s/proprietary/libGLESv1_CM_adreno200.so:system/lib/egl/libGLESv1_CM_adreno200.so \
	vendor/pantech/a760s/proprietary/libGLESv2_adreno200.so:system/lib/egl/libGLESv2_adreno200.so \
	vendor/pantech/a760s/proprietary/libGLESv2S3D_adreno200.so:system/lib/egl/libGLESv2S3D_adreno200.so \
	vendor/pantech/a760s/proprietary/libq3dtools_adreno200.so:system/lib/egl/libq3dtools_adreno200.so \
	vendor/pantech/a760s/proprietary/libacdbmapper.so:system/lib/libacdbmapper.so \
	vendor/pantech/a760s/proprietary/libaudcal.so:system/lib/libaudcal.so \
	vendor/pantech/a760s/proprietary/libaudioalsa.so:system/lib/libaudioalsa.so \
	vendor/pantech/a760s/proprietary/libC2D2.so:system/lib/libC2D2.so \
	vendor/pantech/a760s/proprietary/libacdbloader.so:system/lib/libacdbloader.so \
	vendor/pantech/a760s/proprietary/libdiag.so:system/lib/libdiag.so \
	vendor/pantech/a760s/proprietary/libmmstereo.so:system/lib/libmmstereo.so \
	vendor/pantech/a760s/proprietary/libmpl.so:system/lib/libmpl.so \
	vendor/pantech/a760s/proprietary/libcamera_client.so:system/lib/libcamera_client.so \
	vendor/pantech/a760s/proprietary/libdsutils.so:system/lib/libdsutils.so \
	vendor/pantech/a760s/proprietary/libgemini.so:system/lib/libgemini.so \
	vendor/pantech/a760s/proprietary/libdsm.so:system/lib/libdsm.so \
	vendor/pantech/a760s/proprietary/liboncrpc.so:system/lib/liboncrpc.so \
	vendor/pantech/a760s/proprietary/libqueue.so:system/lib/libqueue.so \
	vendor/pantech/a760s/proprietary/libthermal_mitigation.so:system/lib/libthermal_mitigation.so \
	vendor/pantech/a760s/proprietary/libthermal_mitigation_fusion.so:system/lib/libthermal_mitigation_fusion.so \
	vendor/pantech/a760s/proprietary/libgsl.so:system/lib/libgsl.so \
	vendor/pantech/a760s/proprietary/libidl.so:system/lib/libidl.so \
	vendor/pantech/a760s/proprietary/libmllite.so:system/lib/libmllite.so \
	vendor/pantech/a760s/proprietary/libmlplatform.so:system/lib/libmlplatform.so \
	vendor/pantech/a760s/proprietary/libmm-color-convertor.so:system/lib/libmm-color-convertor.so \
	vendor/pantech/a760s/proprietary/libmmipl.so:system/lib/libmmipl.so \
	vendor/pantech/a760s/proprietary/libmmjpeg.so:system/lib/libmmjpeg.so \
	vendor/pantech/a760s/proprietary/libmmjps.so:system/lib/libmmjps.so \
	vendor/pantech/a760s/proprietary/libmmmpo.so:system/lib/libmmmpo.so \
	vendor/pantech/a760s/proprietary/libmm-omxcore.so:system/lib/libmm-omxcore.so \
	vendor/pantech/a760s/proprietary/libnetmgr.so:system/lib/libnetmgr.so \
	vendor/pantech/a760s/proprietary/liboemcamera.so:system/lib/liboemcamera.so \
	vendor/pantech/a760s/proprietary/libOlaEngine.so:system/lib/libOlaEngine.so \
	vendor/pantech/a760s/proprietary/libOpenMAXAL.so:system/lib/libOpenMAXAL.so \
	vendor/pantech/a760s/proprietary/libOpenSLES.so:system/lib/libOpenSLES.so \
	vendor/pantech/a760s/proprietary/libOpenVG.so:system/lib/libOpenVG.so \
	vendor/pantech/a760s/proprietary/liboverlay.so:system/lib/liboverlay.so \
	vendor/pantech/a760s/proprietary/libqc-opt.so:system/lib/libqc-opt.so \
	vendor/pantech/a760s/proprietary/libqdp.so:system/lib/libqdp.so \
	vendor/pantech/a760s/proprietary/libqmi.so:system/lib/libqmi.so \
	vendor/pantech/a760s/proprietary/libqmiservices.so:system/lib/libqmiservices.so \
	vendor/pantech/a760s/proprietary/libsc-a2xx.so:system/lib/libsc-a2xx.so \
	vendor/pantech/a760s/proprietary/libv8.so:system/lib/libv8.so \
	vendor/pantech/a760s/proprietary/libdsi_netctrl.so:system/lib/libdsi_netctrl.so \
	vendor/pantech/a760s/proprietary/liboem_rapi.so:system/lib/liboem_rapi.so \
	vendor/pantech/a760s/proprietary/liboem_rapi_fusion.so:system/lib/liboem_rapi_fusion.so \
	vendor/pantech/a760s/proprietary/libqdi.so:system/lib/libqdi.so \
	vendor/pantech/a760s/proprietary/libril-qc-qmi-1.so:system/lib/libril-qc-qmi-1.so \
	vendor/pantech/a760s/proprietary/libril-qcril-hook-oem.so:system/lib/libril-qcril-hook-oem.so \
	vendor/pantech/a760s/proprietary/libsky_rawdata.so:system/lib/libsky_rawdata.so \
	vendor/pantech/a760s/proprietary/libskytestclient.so:system/lib/libskytestclient.so \
	vendor/pantech/a760s/proprietary/libDivxDrm.so:system/lib/libDivxDrm.so \
	vendor/pantech/a760s/proprietary/libmmosal.so:system/lib/libmmosal.so \
	vendor/pantech/a760s/proprietary/libmmparser.so:system/lib/libmmparser.so \
	vendor/pantech/a760s/proprietary/libril.so:system/lib/libril.so \
	vendor/pantech/a760s/proprietary/libloc_adapter.so:system/lib/libloc_adapter.so \
	vendor/pantech/a760s/proprietary/libloc_eng.so:system/lib/libloc_eng.so \
	vendor/pantech/a760s/proprietary/libloc_ext.so:system/lib/libloc_ext.so

# bin
PRODUCT_COPY_FILES += \
	vendor/pantech/a760s/proprietary/battery_charging:system/bin/battery_charging \
	vendor/pantech/a760s/proprietary/mpdecision:system/bin/mpdecision \
	vendor/pantech/a760s/proprietary/netmgrd:system/bin/netmgrd \
	vendor/pantech/a760s/proprietary/qmiproxy:system/bin/qmiproxy \
	vendor/pantech/a760s/proprietary/qmuxd:system/bin/qmuxd \
	vendor/pantech/a760s/proprietary/rmt_storage:system/bin/rmt_storage \
	vendor/pantech/a760s/proprietary/thermald:system/bin/thermald \
	vendor/pantech/a760s/proprietary/usbhub:system/bin/usbhub \
	vendor/pantech/a760s/proprietary/usbhub_init:system/bin/usbhub_init \
	vendor/pantech/a760s/proprietary/usb_manager:system/bin/usb_manager \
	vendor/pantech/a760s/proprietary/mm-qcamera-daemon:system/bin/mm-qcamera-daemon \
	vendor/pantech/a760s/proprietary/mm-qcamera-test:system/bin/mm-qcamera-test \
	vendor/pantech/a760s/proprietary/mm-qcamera-testsuite-client:system/bin/mm-qcamera-testsuite-client \
	vendor/pantech/a760s/proprietary/rild:system/bin/rild \
	vendor/pantech/a760s/proprietary/v4l2-qcamera-app:system/bin/v4l2-qcamera-app \
	vendor/pantech/a760s/proprietary/btld:system/bin/btld \
	vendor/pantech/a760s/proprietary/profiler_daemon:system/bin/profiler_daemon \
	vendor/pantech/a760s/proprietary/sensors.qcom:system/bin/sensors.qcom \
	vendor/pantech/a760s/proprietary/cpmgrif:system/bin/cpmgrif
